version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "order-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1xerpuq1bai7"
s3_prefix = "order-app"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
