AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  order-app

  Sample SAM Template for order-app
  
Globals:
  Function:
    Timeout: 3

Resources:
  OrderManagementSFN:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: src/order-management/statemachine/process-order.asl.json
      DefinitionSubstitutions:
        ManageStateArn: !GetAtt ManageStateFunction.Arn
        ProcessPaymentArn: !GetAtt ProcessPaymentFumction.Arn
        SendOrderToRestaurantArn: !GetAtt SendOrderToRestaurantFunction.Arn
      Policies: 
        - LambdaInvokePolicy:
            FunctionName: !Ref ManageStateFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessPaymentFumction
        - LambdaInvokePolicy:
            FunctionName: !Ref SendOrderToRestaurantFunction

  ManageStateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/order-management/functions/managestate/
      Handler: app.manageState
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
          SNS_TOPIC_ARN: !Ref OrderTopic
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query 
              - dynamodb:Scan
              - dynamodb:PutItem
              - dynamodb:UpdateItem
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    
          - Effect: Allow
            Action:
              - SNS:Publish
            Resource:
              - "*"    
  
  OrderTopic:
    Type: AWS::SNS::Topic
    Properties: 
      Subscription: 
        - Endpoint: "frasitkilic@gmail.com"
          Protocol: "email"
      TopicName: "order-topic"


  SendOrderToRestaurantFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/order-management/functions/sendordertorestaurant/
      Handler: app.sendOrderToRestaurant
      Runtime: nodejs14.x

  ProcessPaymentFumction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/order-management/functions/process-payment/
      Handler: app.processPayment
      Runtime: nodejs14.x

  OrderQueue:
    Type: AWS::SQS::Queue
    Properties: 
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt OrderDLQueue.Arn
        maxReceiveCount: 5

  OrderDLQueue:
    Type: AWS::SQS::Queue

  PostOrders:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/order-api/functions/post-orders/
      Handler: app.postOrders
      Runtime: nodejs14.x
      Events:
        SQSEventSource:
          Type: SQS
          Properties:
            Queue: !GetAtt OrderQueue.Arn
            BatchSize: 10
      Environment:
        Variables:
          STATE_MACHINE_ARN: !Ref OrderManagementSFN
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    
          - Effect: Allow
            Action:
              - states:StartExecution
            Resource:
              - !Sub 
                - '${StateMachine}'
                - { StateMachine: !Ref OrderManagementSFN }
 

  OrderApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Cors:
        AllowMethods: "'POST, GET, UPDATE, DELETE'"
        AllowHeaders: "'X-Forwarded-For'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  ApiGwExecutionRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "apigateway.amazonaws.com"
                - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      Path: "/"

  ApiGwExecutionPolicy: 
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "apigw-execution-policy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          Action:
            - sqs:SendMessage
            - lambda:*
          Effect: Allow
          Resource:
            - !GetAtt OrderQueue.Arn
            - !GetAtt PostOrders.Arn

      Roles: 
        - Ref: "ApiGwExecutionRole"


  GetOrders:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/order-api/functions/get-orders/
      Handler: app.getOrders
      Runtime: nodejs14.x
      Environment:
        Variables:
          ORDER_TABLE: !Ref OrderTable
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:Query 
              - dynamodb:Scan
            Resource:
              - !Sub 
                - 'arn:aws:dynamodb:*:*:table/${Table}'
                - { Table: !Ref OrderTable }
          - Effect: Allow
            Action:
              - logs:*
            Resource:
              - "*"    


  OrderTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: order-table
      AttributeDefinitions: 
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5


Outputs:
  OrderQueueUrl: 
    Description: "URL of order queue"
    Value: !Ref OrderDLQueue
  OrderDLQueueUrl: 
    Description: "URL of order dead-letter queue"
    Value: !Ref OrderDLQueue

  PostOrders:
    Description: "PostOrders Lambda Function ARN"
    Value: !GetAtt PostOrders.Arn

  OrderApiEndpoint:
    Description: "API Gateway endpoint URL for Dev stage for Order Get function"
    Value: !Sub "https://${OrderApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/orders/"

  GetOrders:
    Description: "GetOrders Lambda Function ARN"
    Value: !GetAtt GetOrders.Arn

  DynamoDBTableName:
    Description: "DynamoDB Table Name"
    Value: !Ref OrderTable


